### ISSUE TITLE
ImportError: No module named 'CommandFactory'

### ISSUE THREAD

**Issue by yvan-sraka** [cappuccino-app/cappuccino-server#43]
```shell
yvan@x230:~/Cappuccino/cappuccino-server$ chmod +x run.sh
yvan@x230:~/Cappuccino/cappuccino-server$ ./run.sh 
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0a39691ae8>
Traceback (most recent call last):
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/yvan/Cappuccino/cappuccino-server/cappuccino/urls.py", line 15, in <module>
    url(r'^', include('cappuccino.apps.command.urls')),
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/yvan/Cappuccino/cappuccino-server/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/yvan/Cappuccino/cappuccino-server/cappuccino/apps/command/urls.py", line 2, in <module>
    from . import views
  File "/home/yvan/Cappuccino/cappuccino-server/cappuccino/apps/command/views.py", line 13, in <module>
    from CommandFactory import *
ImportError: No module named 'CommandFactory'
```

**Comment by yvan-sraka** [comment]
I don't think that's normal :open_mouth:!?

**Comment by MattiaPrimavera** [comment]
Just because it's easier for u since u see the error ... Yesterday I had
the opposite problem and i had to uncomment it in order for the program to
work ...
Le 2016-08-14 13:15, sconqua@gmail.com a écrit :

Fuck but I fixed this yesterday! Can u do that pls? It's gonna be easy
Le 2016-08-14 10:02, "Yvan Sraka" <notifications@github.com> a écrit :

Assigned #43 <https://github.com/cappuccino-app/cappuccino-server/issues/43>
to @MattiaPrimavera <https://github.com/MattiaPrimavera>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cappuccino-app/cappuccino-server/issues/43#event-754975225>,
or mute the thread

**Comment by MattiaPrimavera** [comment]
Fuck but I fixed this yesterday! Can u do that pls? It's gonna be easy

**Comment by yvan-sraka** [comment]
Do what?

**Comment by MattiaPrimavera** [comment]
Could u check if this needs to be closed? Cause i had that error yesterday
night and normally fixed it by uncommenting the import line

**Comment by yvan-sraka** [comment]
No, you don't understand: I have the problem if I keep the line uncommented, I solve it by commenting the line..

**Comment by MattiaPrimavera** [comment]
For me it's exactly the opposite ... How is it possible ^^`

**Comment by yvan-sraka** [comment]
That's our job to understand that!
I don't see where the module `CommandFactory` is use in the file `apps/command/views.py`?

**Comment by MattiaPrimavera** [comment]
Here's where it's called ...
```python
commandObject = CommandFactory().createCommand(command)
```

But the `import statement` was not correct:
it should have been
```python
from CommandFactory import CommandFactory
```

in order for the actual code to work, now it's fixed.
